//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.Entities.Editor {
    using System;
    
    
    public partial class BurstInteropCodeGenerator : CodeGeneratorBase {
        
        public override string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 2 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n//-----------------------------------------------------------------------------" +
                    "-\r\n// <auto-generated>\r\n//     This file was automatically generated by ");
            
            #line default
            #line hidden
            
            #line 5 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetType()));
            
            #line default
            #line hidden
            
            #line 5 "BurstInteropCodeGenerator.tt"
            this.Write(@"
//     Any changes you make here will be overwritten
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     To update this file, use the ""DOTS -> Regenerate Burst Interop"" menu option.
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Unity.Burst;
using Unity.Collections;
using System.Runtime.InteropServices;
using Unity.Collections.LowLevel.Unsafe;

namespace ");
            
            #line default
            #line hidden
            
            #line 22 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( StructType.Namespace ));
            
            #line default
            #line hidden
            
            #line 22 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n{\r\n    ");
            
            #line default
            #line hidden
            
            #line 24 "BurstInteropCodeGenerator.tt"
 if (StructType.IsPublic) {
            
            #line default
            #line hidden
            
            #line 25 "BurstInteropCodeGenerator.tt"
            this.Write("public");
            
            #line default
            #line hidden
            
            #line 25 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 26 "BurstInteropCodeGenerator.tt"
            this.Write(" unsafe partial struct ");
            
            #line default
            #line hidden
            
            #line 26 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( StructType.Name ));
            
            #line default
            #line hidden
            
            #line 26 "BurstInteropCodeGenerator.tt"
            this.Write(@"
    {

#if !UNITY_IOS

        [BurstDiscard]
        private static void CheckDelegate(ref bool useDelegate)
        {
            //@TODO: This should use BurstCompiler.IsEnabled once that is available as an efficient API.
            useDelegate = true;
        }

        private static bool UseDelegate()
        {
            bool result = false;
            CheckDelegate(ref result);
            return result;
        }

        static class Managed
        {
            public static bool _initialized = false;

");
            
            #line default
            #line hidden
            
            #line 49 "BurstInteropCodeGenerator.tt"
 foreach (var method in BurstTargetMethods) { 
            
            #line default
            #line hidden
            
            #line 50 "BurstInteropCodeGenerator.tt"
            this.Write("            public delegate ");
            
            #line default
            #line hidden
            
            #line 50 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ReturnType(method) ));
            
            #line default
            #line hidden
            
            #line 50 "BurstInteropCodeGenerator.tt"
            this.Write(" _dlg");
            
            #line default
            #line hidden
            
            #line 50 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 50 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 50 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrototypeForDelegate(method) ));
            
            #line default
            #line hidden
            
            #line 50 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n            public static _dlg");
            
            #line default
            #line hidden
            
            #line 51 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 51 "BurstInteropCodeGenerator.tt"
            this.Write(" _bfp");
            
            #line default
            #line hidden
            
            #line 51 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 51 "BurstInteropCodeGenerator.tt"
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 52 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 53 "BurstInteropCodeGenerator.tt"
 foreach (var method in MonoTargetMethods) { 
            
            #line default
            #line hidden
            
            #line 54 "BurstInteropCodeGenerator.tt"
            this.Write("            public delegate ");
            
            #line default
            #line hidden
            
            #line 54 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ReturnType(method) ));
            
            #line default
            #line hidden
            
            #line 54 "BurstInteropCodeGenerator.tt"
            this.Write(" _dlg");
            
            #line default
            #line hidden
            
            #line 54 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 54 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 54 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrototypeForDelegate(method) ));
            
            #line default
            #line hidden
            
            #line 54 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n            public static object _gcDefeat");
            
            #line default
            #line hidden
            
            #line 55 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 55 "BurstInteropCodeGenerator.tt"
            this.Write(";\r\n");
            
            #line default
            #line hidden
            
            #line 56 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 57 "BurstInteropCodeGenerator.tt"
            this.Write("        }\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 59 "BurstInteropCodeGenerator.tt"
 foreach (var method in MonoTargetMethods) { 
            
            #line default
            #line hidden
            
            #line 60 "BurstInteropCodeGenerator.tt"
            this.Write("        struct TagType");
            
            #line default
            #line hidden
            
            #line 60 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name));
            
            #line default
            #line hidden
            
            #line 60 "BurstInteropCodeGenerator.tt"
            this.Write(" {};\r\n        public static readonly SharedStatic<IntPtr> _bfp");
            
            #line default
            #line hidden
            
            #line 61 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 61 "BurstInteropCodeGenerator.tt"
            this.Write(" = SharedStatic<IntPtr>.GetOrCreate<TagType");
            
            #line default
            #line hidden
            
            #line 61 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 61 "BurstInteropCodeGenerator.tt"
            this.Write(">();\r\n");
            
            #line default
            #line hidden
            
            #line 62 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 63 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n#endif\r\n\r\n        [NotBurstCompatible]\r\n        internal static void Initialize" +
                    "()\r\n        {\r\n#if !UNITY_IOS\r\n            if (Managed._initialized)\r\n          " +
                    "      return;\r\n            Managed._initialized = true;\r\n");
            
            #line default
            #line hidden
            
            #line 73 "BurstInteropCodeGenerator.tt"

   foreach (var method in BurstTargetMethods)
   {

            
            #line default
            #line hidden
            
            #line 77 "BurstInteropCodeGenerator.tt"
            this.Write("            Managed._bfp");
            
            #line default
            #line hidden
            
            #line 77 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 77 "BurstInteropCodeGenerator.tt"
            this.Write(" = BurstCompiler.CompileFunctionPointer<Managed._dlg");
            
            #line default
            #line hidden
            
            #line 77 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 77 "BurstInteropCodeGenerator.tt"
            this.Write(">(_mono_to_burst");
            
            #line default
            #line hidden
            
            #line 77 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 77 "BurstInteropCodeGenerator.tt"
            this.Write(").Invoke;\r\n");
            
            #line default
            #line hidden
            
            #line 78 "BurstInteropCodeGenerator.tt"

   }
            
            #line default
            #line hidden
            
            #line 80 "BurstInteropCodeGenerator.tt"

   foreach (var method in MonoTargetMethods)
   {

            
            #line default
            #line hidden
            
            #line 84 "BurstInteropCodeGenerator.tt"
            this.Write("        {\r\n            Managed._dlg");
            
            #line default
            #line hidden
            
            #line 85 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 85 "BurstInteropCodeGenerator.tt"
            this.Write(" delegateObject = _wrapper");
            
            #line default
            #line hidden
            
            #line 85 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 85 "BurstInteropCodeGenerator.tt"
            this.Write(";\r\n            Managed._gcDefeat");
            
            #line default
            #line hidden
            
            #line 86 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 86 "BurstInteropCodeGenerator.tt"
            this.Write(" = delegateObject;\r\n            _bfp");
            
            #line default
            #line hidden
            
            #line 87 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 87 "BurstInteropCodeGenerator.tt"
            this.Write(".Data = Marshal.GetFunctionPointerForDelegate(delegateObject);\r\n        }\r\n");
            
            #line default
            #line hidden
            
            #line 89 "BurstInteropCodeGenerator.tt"

   }
            
            #line default
            #line hidden
            
            #line 91 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n#endif\r\n        }\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 95 "BurstInteropCodeGenerator.tt"
 foreach (var method in BurstTargetMethods) { 
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GetAccessibility(method) ));
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write("  static ");
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ReturnType(method) ));
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name.Substring(1) ));
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write(" (");
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Prototype(method) ));
            
            #line default
            #line hidden
            
            #line 96 "BurstInteropCodeGenerator.tt"
            this.Write(")\r\n        {\r\n#if !UNITY_IOS\r\n            if (UseDelegate())\r\n            {\r\n");
            
            #line default
            #line hidden
            
            #line 101 "BurstInteropCodeGenerator.tt"
if (method.ReturnType == typeof(void)) {
            
            #line default
            #line hidden
            
            #line 102 "BurstInteropCodeGenerator.tt"
            this.Write("                _forward_mono");
            
            #line default
            #line hidden
            
            #line 102 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 102 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 102 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgs(method) ));
            
            #line default
            #line hidden
            
            #line 102 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n                return;\r\n");
            
            #line default
            #line hidden
            
            #line 104 "BurstInteropCodeGenerator.tt"
} else {
            
            #line default
            #line hidden
            
            #line 105 "BurstInteropCodeGenerator.tt"
            this.Write("                var _retval = default(");
            
            #line default
            #line hidden
            
            #line 105 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ReturnType(method)));
            
            #line default
            #line hidden
            
            #line 105 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n                _forward_mono");
            
            #line default
            #line hidden
            
            #line 106 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 106 "BurstInteropCodeGenerator.tt"
            this.Write("(ref _retval, ");
            
            #line default
            #line hidden
            
            #line 106 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgs(method) ));
            
            #line default
            #line hidden
            
            #line 106 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n                return _retval;\r\n");
            
            #line default
            #line hidden
            
            #line 108 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 109 "BurstInteropCodeGenerator.tt"
            this.Write("            }\r\n#endif\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 112 "BurstInteropCodeGenerator.tt"
if (method.ReturnType == typeof(void)) {
            
            #line default
            #line hidden
            
            #line 113 "BurstInteropCodeGenerator.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 113 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 113 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 113 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgs(method) ));
            
            #line default
            #line hidden
            
            #line 113 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n");
            
            #line default
            #line hidden
            
            #line 114 "BurstInteropCodeGenerator.tt"
} else {
            
            #line default
            #line hidden
            
            #line 115 "BurstInteropCodeGenerator.tt"
            this.Write("            return ");
            
            #line default
            #line hidden
            
            #line 115 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 115 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 115 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgs(method) ));
            
            #line default
            #line hidden
            
            #line 115 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n");
            
            #line default
            #line hidden
            
            #line 116 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 117 "BurstInteropCodeGenerator.tt"
            this.Write("        }\r\n\r\n#if !UNITY_IOS\r\n        [BurstCompile]\r\n        [MonoPInvokeCallback" +
                    "(typeof(Managed._dlg");
            
            #line default
            #line hidden
            
            #line 121 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 121 "BurstInteropCodeGenerator.tt"
            this.Write("))]\r\n        private static ");
            
            #line default
            #line hidden
            
            #line 122 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ReturnType(method) ));
            
            #line default
            #line hidden
            
            #line 122 "BurstInteropCodeGenerator.tt"
            this.Write(" _mono_to_burst");
            
            #line default
            #line hidden
            
            #line 122 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 122 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 122 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrototypeForDelegate(method) ));
            
            #line default
            #line hidden
            
            #line 122 "BurstInteropCodeGenerator.tt"
            this.Write(")\r\n        {\r\n");
            
            #line default
            #line hidden
            
            #line 124 "BurstInteropCodeGenerator.tt"
if (method.ReturnType == typeof(void)) {
            
            #line default
            #line hidden
            
            #line 125 "BurstInteropCodeGenerator.tt"
            this.Write("            ");
            
            #line default
            #line hidden
            
            #line 125 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 125 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 125 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgsMonoToBurst(method) ));
            
            #line default
            #line hidden
            
            #line 125 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n");
            
            #line default
            #line hidden
            
            #line 126 "BurstInteropCodeGenerator.tt"
} else {
            
            #line default
            #line hidden
            
            #line 127 "BurstInteropCodeGenerator.tt"
            this.Write("            return ");
            
            #line default
            #line hidden
            
            #line 127 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 127 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 127 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgsMonoToBurst(method) ));
            
            #line default
            #line hidden
            
            #line 127 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n");
            
            #line default
            #line hidden
            
            #line 128 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 129 "BurstInteropCodeGenerator.tt"
            this.Write("        }\r\n\r\n        [BurstDiscard]\r\n");
            
            #line default
            #line hidden
            
            #line 132 "BurstInteropCodeGenerator.tt"
 if (method.ReturnType == typeof(void)) { 
            
            #line default
            #line hidden
            
            #line 133 "BurstInteropCodeGenerator.tt"
            this.Write("        private static void _forward_mono");
            
            #line default
            #line hidden
            
            #line 133 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 133 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 133 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Prototype(method) ));
            
            #line default
            #line hidden
            
            #line 133 "BurstInteropCodeGenerator.tt"
            this.Write(")\r\n");
            
            #line default
            #line hidden
            
            #line 134 "BurstInteropCodeGenerator.tt"
} else {
            
            #line default
            #line hidden
            
            #line 135 "BurstInteropCodeGenerator.tt"
            this.Write("        private static void _forward_mono");
            
            #line default
            #line hidden
            
            #line 135 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 135 "BurstInteropCodeGenerator.tt"
            this.Write("(ref ");
            
            #line default
            #line hidden
            
            #line 135 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ReturnType(method) ));
            
            #line default
            #line hidden
            
            #line 135 "BurstInteropCodeGenerator.tt"
            this.Write(" _retval, ");
            
            #line default
            #line hidden
            
            #line 135 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Prototype(method) ));
            
            #line default
            #line hidden
            
            #line 135 "BurstInteropCodeGenerator.tt"
            this.Write(")\r\n");
            
            #line default
            #line hidden
            
            #line 136 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 137 "BurstInteropCodeGenerator.tt"
            this.Write("        {\r\n");
            
            #line default
            #line hidden
            
            #line 138 "BurstInteropCodeGenerator.tt"
if (method.ReturnType == typeof(void)) {
            
            #line default
            #line hidden
            
            #line 139 "BurstInteropCodeGenerator.tt"
            this.Write("            Managed._bfp");
            
            #line default
            #line hidden
            
            #line 139 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 139 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 139 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgsForwardMono(method) ));
            
            #line default
            #line hidden
            
            #line 139 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n");
            
            #line default
            #line hidden
            
            #line 140 "BurstInteropCodeGenerator.tt"
} else {
            
            #line default
            #line hidden
            
            #line 141 "BurstInteropCodeGenerator.tt"
            this.Write("            _retval = Managed._bfp");
            
            #line default
            #line hidden
            
            #line 141 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name));
            
            #line default
            #line hidden
            
            #line 141 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 141 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgsForwardMono(method) ));
            
            #line default
            #line hidden
            
            #line 141 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n");
            
            #line default
            #line hidden
            
            #line 142 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 143 "BurstInteropCodeGenerator.tt"
            this.Write("        }\r\n#endif\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 146 "BurstInteropCodeGenerator.tt"
}
            
            #line default
            #line hidden
            
            #line 147 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n");
            
            #line default
            #line hidden
            
            #line 148 "BurstInteropCodeGenerator.tt"

   foreach (var method in MonoTargetMethods)
   {

            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write("        ");
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( GetAccessibility(method) ));
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(" static ");
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ReturnType(method) ));
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(" ");
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name.Substring(1) ));
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(" (");
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Prototype(method) ));
            
            #line default
            #line hidden
            
            #line 152 "BurstInteropCodeGenerator.tt"
            this.Write(")\r\n        {\r\n#if !UNITY_IOS\r\n            if (!UseDelegate())\r\n            {\r\n#if" +
                    " ENABLE_UNITY_COLLECTIONS_CHECKS\r\n                if( _bfp");
            
            #line default
            #line hidden
            
            #line 158 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 158 "BurstInteropCodeGenerator.tt"
            this.Write(".Data == IntPtr.Zero)\r\n                    throw new InvalidOperationException(\"B" +
                    "urst Interop Classes must be initialized manually\");\r\n#endif\r\n\r\n                " +
                    "var fp = new FunctionPointer<Managed._dlg");
            
            #line default
            #line hidden
            
            #line 162 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 162 "BurstInteropCodeGenerator.tt"
            this.Write(">(_bfp");
            
            #line default
            #line hidden
            
            #line 162 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 162 "BurstInteropCodeGenerator.tt"
            this.Write(".Data);\r\n                fp.Invoke(");
            
            #line default
            #line hidden
            
            #line 163 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgsForwardMono(method) ));
            
            #line default
            #line hidden
            
            #line 163 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n                return;\r\n            }\r\n#endif\r\n            ");
            
            #line default
            #line hidden
            
            #line 167 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name ));
            
            #line default
            #line hidden
            
            #line 167 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 167 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgs(method) ));
            
            #line default
            #line hidden
            
            #line 167 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n        }\r\n\r\n#if !UNITY_IOS\r\n        [MonoPInvokeCallback(typeof(Managed._dlg" +
                    "");
            
            #line default
            #line hidden
            
            #line 171 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 171 "BurstInteropCodeGenerator.tt"
            this.Write("))]\r\n#endif\r\n        private static ");
            
            #line default
            #line hidden
            
            #line 173 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( ReturnType(method) ));
            
            #line default
            #line hidden
            
            #line 173 "BurstInteropCodeGenerator.tt"
            this.Write(" _wrapper");
            
            #line default
            #line hidden
            
            #line 173 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( method.Name ));
            
            #line default
            #line hidden
            
            #line 173 "BurstInteropCodeGenerator.tt"
            this.Write(" (");
            
            #line default
            #line hidden
            
            #line 173 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( PrototypeForDelegate(method) ));
            
            #line default
            #line hidden
            
            #line 173 "BurstInteropCodeGenerator.tt"
            this.Write(")\r\n        {\r\n            ");
            
            #line default
            #line hidden
            
            #line 175 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(method.Name ));
            
            #line default
            #line hidden
            
            #line 175 "BurstInteropCodeGenerator.tt"
            this.Write("(");
            
            #line default
            #line hidden
            
            #line 175 "BurstInteropCodeGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( CallArgsMonoToBurst(method) ));
            
            #line default
            #line hidden
            
            #line 175 "BurstInteropCodeGenerator.tt"
            this.Write(");\r\n        }\r\n");
            
            #line default
            #line hidden
            
            #line 177 "BurstInteropCodeGenerator.tt"

   } 
            
            #line default
            #line hidden
            
            #line 179 "BurstInteropCodeGenerator.tt"
            this.Write("\r\n\r\n    }\r\n}\r\n");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public override void Initialize() {
            base.Initialize();
        }
    }
}
